- name: InfluxDB | Fetch package
  get_url: url=http://s3.amazonaws.com/influxdb/influxdb_{{ influxdb.version }}_amd64.deb dest=/usr/local/src/influxdb_{{ influxdb.version }}_amd64.deb

- name: InfluxDB | Install package
  command: dpkg --skip-same-version -i /usr/local/src/influxdb_{{ influxdb.version }}_amd64.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"

- name: InfluxDB | Link influx CLI
  file: src=/opt/influxdb/influx dest=/usr/local/bin/influx state=link

- name: InfluxDB | Check for ip address in config file
  command: grep -E '^\s*hostname.*{{ ansible_default_ipv4.address }}' /opt/influxdb/shared/config.toml
  register: config_has_ip
  ignore_errors: true
  changed_when: false

- name: InfluxDB | Delete raft dir before hostname change
  file: dest=/opt/influxdb/shared/data/raft state=absent
  when: config_has_ip|failed

- name: InfluxDB | Start Service
  service: name=influxdb state=started

- name: InfluxDB | Update config
  template: src={{ influxdb.config_tpl }} dest=/etc/opt/influxdb/influxdb.conf
  notify:
    - restart influxdb
