- name: InfluxDB | Fetch package | Debian
  get_url: url=http://s3.amazonaws.com/influxdb/influxdb_{{ influxdb.version }}-1_amd64.deb dest=/usr/local/src/influxdb_{{ influxdb.version }}-1_amd64.deb
  when: ansible_os_family == "Debian"

- name: InfluxDB | Install package | Debian
  command: dpkg --skip-same-version -i /usr/local/src/influxdb_{{ influxdb.version }}-1_amd64.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  when: ansible_os_family == "Debian"

- name: InfluxDB | Fetch package | RedHat
  get_url: url=https://s3.amazonaws.com/influxdb/influxdb-{{ influxdb.version }}-1.x86_64.rpm dest=/usr/local/src/influxdb_{{ influxdb.version }}-1.x86_64.rpm
  when: ansible_os_family == "RedHat"

- name: InfluxDB | Install package | RedHat
  yum: name=/usr/local/src/influxdb_{{ influxdb.version }}-1.x86_64.rpm state=installed
  when: ansible_os_family == "RedHat"

- name: InfluxDB | Check for ip address in config file
  command: grep -E '^\s*hostname.*{{ ansible_default_ipv4.address }}' /etc/opt/influxdb/influxdb.conf
  register: config_has_ip
  ignore_errors: true
  changed_when: false

- name: InfluxDB | Delete raft dir before hostname change
  file: dest=/opt/influxdb/shared/data/raft state=absent
  when: config_has_ip|failed

- name: InfluxDB | Start Service
  service: name=influxdb state=started

- name: InfluxDB | Update config
  template: src={{ influxdb.config_tpl }} dest=/etc/influxdb/influxdb.conf
  notify:
    - restart influxdb
